### PR TITLE
Add BoF MIMI informative reference

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Add BoF MIMI informative reference

### CODE REVIEW

**Comment by turt2live** [comment]
I'm a bit new to the IETF processes: what is this achieving specifically? (I'm a bit surprised to see the BoF referenced instead of a landing page for the working group).

**Comment by soroshsabz** [comment]
I'm literally new to the IETF processes ;) but I think every new concept and keyword need a reference to capable readers to explore more information about that, so I think until IETF standard entire MIMI, we have to refer to BoF

thanks

**Comment by soroshsabz** [comment]
@turt2live any update?

**Comment by turt2live** [comment]
This doesn't feel like the right link or use of references to me. I can't find any information on the IETF side to say if this is correct or not, but am favouring not changing anything for now.

**Comment by turt2live** [comment]
I'm not sure this reference is required. Closing in the meantime (though happy to be pointed to where it makes sense to include such a reference).

**Pull request closed without merging**
